/**
 * Mock LLM responses for testing without API access.
 * Activated by setting MEMEX_MOCK=1 environment variable.
 */

export const MOCK_ANALYSIS = {
  summary: "A comprehensive guide to building LLM-powered persistent knowledge bases using a wiki pattern.",
  keyTopics: ["llm-wiki", "rag", "knowledge-management", "memex", "persistent-memory"],
  pagesToWrite: [
    {
      name: "concepts/llm-wiki-pattern",
      title: "LLM Wiki Pattern",
      summary: "The core pattern for building persistent, compounding knowledge bases with LLMs",
      tags: ["concept", "llm", "wiki", "pattern"],
      action: "create",
      reason: "Core concept of the source document"
    },
    {
      name: "concepts/knowledge-base-architecture",
      title: "Knowledge Base Architecture",
      summary: "Three-layer architecture: raw sources, wiki, and schema",
      tags: ["architecture", "concept"],
      action: "create",
      reason: "Describes the three-layer architecture"
    },
    {
      name: "concepts/ingest-workflow",
      title: "Ingest Workflow",
      summary: "How to process new sources into the wiki",
      tags: ["workflow", "ingest"],
      action: "create",
      reason: "Core operational workflow"
    }
  ],
  contradictions: []
};

export const MOCK_PAGE_CONTENT = (pageName, title) => `---
title: "${title}"
tags: [concept, llm, wiki]
summary: "Mock page for ${title}"
sources: []
updated: "${new Date().toISOString().split('T')[0]}"
---

# ${title}

> **Note**: This is a mock page generated for testing purposes.

## Overview

This page covers the key concepts related to ${title}.

## Key Points

- The LLM wiki pattern creates a persistent, compounding knowledge base
- Unlike RAG, knowledge is synthesized once and kept current
- The wiki grows richer with every source added

## Related Pages

- [[concepts/llm-wiki-pattern]]
- [[concepts/knowledge-base-architecture]]
`;

export const MOCK_QUERY_RESPONSE = (question) => `Based on the knowledge base, here is what I found about "${question}":

## Answer

The knowledge base contains relevant information about this topic. The LLM wiki pattern 
described in [[concepts/llm-wiki-pattern]] provides a foundation for understanding this.

Key points from the wiki:
1. Knowledge is compiled once and kept current, not re-derived on every query
2. The wiki is a persistent, compounding artifact
3. Cross-references are pre-built, making synthesis faster

## Sources

- [[concepts/llm-wiki-pattern]]
- [[concepts/knowledge-base-architecture]]
`;

export const MOCK_LINT_RESULT = {
  issues: [
    {
      type: "missing-link",
      severity: "info",
      page: "concepts/llm-wiki-pattern",
      message: "This page could link to the ingest workflow",
      suggestion: "Add [[concepts/ingest-workflow]] reference"
    }
  ],
  suggestedTopics: [
    "Vector embeddings for semantic search",
    "Conflict resolution strategies for contradicting sources",
    "Automated wiki maintenance schedules"
  ]
};

export const MOCK_CONTEXT = (role) => `# Knowledge Base Context

> Generated by memex (mock mode) | Role: ${role || 'general'}

## Core Concepts

The LLM wiki pattern ([[concepts/llm-wiki-pattern]]) builds a persistent knowledge base
where an LLM synthesizes information incrementally rather than re-deriving it on every query.

> **Key Architecture**: Three layers — raw sources (immutable), wiki (LLM-maintained), schema (AGENTS.md)

## Workflows

**Ingest** ([[concepts/ingest-workflow]]): Drop source → LLM reads → extracts key info → updates wiki pages → updates index → logs entry.

**Query**: Read index → find relevant pages → synthesize answer → optionally save as new page.

**Lint**: Find orphan pages, contradictions, stale claims, missing cross-references.

## Key References

- [[wiki/index.md]] — Master index of all pages
- [[AGENTS.md]] — Schema and conventions
- [[concepts/llm-wiki-pattern]] — Core concept
`;
