/**
 * memex sync — Sync knowledge base context to AI agent config files
 * 
 * Generates context and writes it to:
 * - CLAUDE.md (for Claude Code)
 * - .cursorrules (for Cursor)
 * - .github/copilot-instructions.md (for GitHub Copilot)
 * - Custom output file
 */

import { writeFileSync, existsSync, readFileSync } from 'fs';
import { join, resolve } from 'path';
import { format } from 'date-fns';
import ora from 'ora';
import inquirer from 'inquirer';
import chalk from 'chalk';

import { printBanner, printSuccess, printError, printInfo, printWarn, printDivider, printSection } from '../lib/ui.js';
import { getActiveKbPath } from '../lib/config.js';
import { getKbStructure, listWikiPages, readIndex, readSchema, getKbConfig } from '../lib/kb.js';
import { llmCall, estimateTokens } from '../lib/llm.js';
import fsExtra from 'fs-extra';

const { ensureDirSync } = fsExtra;

const AGENT_TARGETS = {
  'claude': {
    file: 'CLAUDE.md',
    description: 'Claude Code',
    header: '<!-- Generated by memex — do not edit manually -->\n',
  },
  'cursor': {
    file: '.cursorrules',
    description: 'Cursor',
    header: '# Generated by memex — do not edit manually\n\n',
  },
  'copilot': {
    file: '.github/copilot-instructions.md',
    description: 'GitHub Copilot',
    header: '<!-- Generated by memex — do not edit manually -->\n',
  },
  'aider': {
    file: 'CONVENTIONS.md',
    description: 'Aider',
    header: '# Generated by memex — do not edit manually\n\n',
  },
};

export async function syncCommand(options) {
  printBanner('memex sync', 'Sync knowledge base context to AI agent config');

  let kbPath;
  try {
    kbPath = getActiveKbPath(options.kb);
  } catch (err) {
    printError(err.message);
    process.exit(1);
  }

  const targetDir = options.dir ? resolve(options.dir) : process.cwd();
  const role = options.role;
  const maxTokens = parseInt(options.maxTokens || '8000', 10);

  // Select target agent(s)
  let targets = [];
  if (options.target) {
    targets = options.target.split(',').map(t => t.trim());
  } else {
    const { selectedTargets } = await inquirer.prompt([{
      type: 'checkbox',
      name: 'selectedTargets',
      message: 'Sync context to which AI agent config files?',
      choices: Object.entries(AGENT_TARGETS).map(([value, { description, file }]) => ({
        value,
        name: `${description} (${file})`,
        checked: value === 'claude',
      })),
    }]);
    targets = selectedTargets;
  }

  if (targets.length === 0) {
    printInfo('No targets selected. Nothing to sync.');
    return;
  }

  // Generate context
  const kbConfig = getKbConfig(kbPath);
  const schema = readSchema(kbPath);
  const index = readIndex(kbPath);

  const loadSpinner = ora('Loading wiki pages...').start();
  let pages;
  try {
    pages = await listWikiPages(kbPath);
    loadSpinner.succeed(`Loaded ${pages.length} page(s)`);
  } catch (err) {
    loadSpinner.fail('Failed to load pages');
    printError(err.message);
    process.exit(1);
  }

  const distillSpinner = ora('Generating context...').start();
  let contextContent;
  try {
    const pageContents = pages.map(p => ({
      name: p.name,
      title: p.title,
      content: readFileSync(p.path, 'utf8'),
    }));

    contextContent = await llmCall(
      buildSyncSystemPrompt(kbConfig, role, maxTokens),
      buildSyncUserPrompt(pageContents, index, role)
    );
    distillSpinner.succeed('Context generated');
  } catch (err) {
    distillSpinner.fail('Context generation failed');
    printError(err.message);
    process.exit(1);
  }

  // Write to each target
  const date = format(new Date(), 'yyyy-MM-dd');
  const tokenCount = estimateTokens(contextContent);

  printDivider();
  for (const target of targets) {
    const targetConfig = AGENT_TARGETS[target];
    if (!targetConfig) {
      printWarn(`Unknown target: ${target}. Skipping.`);
      continue;
    }

    const filePath = join(targetDir, targetConfig.file);
    ensureDirSync(join(targetDir, targetConfig.file.split('/').slice(0, -1).join('/')));

    const fileContent = targetConfig.header +
      `# Knowledge Base: ${kbConfig.name || 'Unnamed'}\n` +
      `# Generated: ${date} | Role: ${role || 'general'} | Tokens: ~${tokenCount}\n\n` +
      contextContent;

    // Check if file exists and warn about overwrite
    if (existsSync(filePath)) {
      const existing = readFileSync(filePath, 'utf8');
      if (!existing.includes('Generated by memex')) {
        printWarn(`${targetConfig.file} exists and was not generated by memex. Appending memex section.`);
        writeFileSync(filePath, existing + '\n\n---\n\n' + fileContent);
      } else {
        writeFileSync(filePath, fileContent);
      }
    } else {
      writeFileSync(filePath, fileContent);
    }

    printSuccess(`Synced to ${targetConfig.file} (${targetConfig.description})`);
  }

  printDivider();
  printInfo(`Estimated tokens: ~${tokenCount.toLocaleString()}`);
  console.log('');
  printSection('Next steps');
  console.log(`  ${chalk.gray('Re-sync after adding new knowledge:')}  memex sync${role ? ` --role ${role}` : ''}`);
  console.log(`  ${chalk.gray('Add more knowledge:')}  memex ingest <source>`);
}

function buildSyncSystemPrompt(kbConfig, role, maxTokens) {
  return `You are generating a concise knowledge context document for an AI coding agent.

Knowledge base: ${kbConfig.name || 'Unnamed'}
${role ? `Target role: ${role}` : 'Target: general use'}
Token budget: ~${maxTokens} tokens

Write a compact, high-signal context document that:
1. Summarizes the most important knowledge from the wiki
2. Lists key decisions, conventions, and best practices
3. Provides [[page-name]] references for deeper reading
4. Is formatted for easy scanning by an AI agent

The document should help the AI agent understand:
- The codebase/domain conventions and decisions
- Key patterns and best practices to follow
- Important context that would otherwise require reading many files

Use markdown with clear sections. Be extremely concise.`;
}

function buildSyncUserPrompt(pageContents, index, role) {
  const pagesText = pageContents
    .slice(0, 15) // limit to 15 most relevant pages
    .map(p => `### [[${p.name}]]\n${p.content.slice(0, 1000)}`)
    .join('\n\n---\n\n');

  return `## Wiki Index
${index}

## Wiki Pages (sample)
${pagesText}

Generate a concise context document${role ? ` for a ${role}` : ''} from this knowledge base.`;
}
